# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
    build-and-test:
        machine:
            image: ubuntu-2204:2024.01.2
        resource_class: xlarge
        steps:
            - checkout
            - run:
                  name: Install
                  command: npm ci
            - setup_remote_docker:
                  version: docker23
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Format
                  command: npm run format-check
            - run:
                  name: Lint
                  command: npm run lint-check
            - run:
                  name: Spawn Devnet
                  command: |
                      echo "preparing to spawn devnet"
                      docker run -d -p 127.0.0.1:5050:5050 --name devnet shardlabs/starknet-devnet-rs:0.1.1 --state-archive-capacity full
                      echo "sleeping..."
                      sleep 3
                      curl localhost:5050/is_alive
                      echo "check done"

            - run:
                  name: Spawn Anvil
                  command: |
                      docker run -d -p 127.0.0.1:8545:8545 --name anvil ghcr.io/foundry-rs/foundry:nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a anvil
                      curl 127.0.0.1:8545 --json '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":67}'
            - run:
                  name: Test
                  command: npm run test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
    build-test:
        jobs:
            - build-and-test
