# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
    build-and-test:
        machine:
            image: ubuntu-2204:2024.01.2
        resource_class: xlarge
        environment:
            FORKED_DEVNET_PORT: 5051
        steps:
            - checkout
            - run:
                  name: Versions
                  command: |
                      echo "node: $(node --version)"
                      echo "npm: $(npm --version)"
            - run:
                  name: Install
                  command: npm ci
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Format
                  command: npm run format-check
            - run:
                  name: Lint
                  command: npm run lint-check
            - run:
                  name: Spawn Devnet
                  command: |
                      docker run -d --network host --name devnet \
                        shardlabs/starknet-devnet-rs:0.1.2 --state-archive-capacity full --dump-on exit --dump-path "dummy.dump.json"
            - run:
                  name: Spawn Devnet forked from Mainnet
                  command: |
                      docker run -d --network host --name forked-devnet \
                        shardlabs/starknet-devnet-rs:0.1.2 --port ${FORKED_DEVNET_PORT} --fork-network https://free-rpc.nethermind.io/mainnet-juno/v0_7
            - run:
                  name: Spawn Anvil
                  command: |
                      docker run -d --network host --name anvil \
                        ghcr.io/foundry-rs/foundry:nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a anvil
            - run:
                  name: Test
                  command: npm run test
    publish:
        docker:
            - image: cimg/node:20.10.0
        steps:
            - checkout
            - run:
                  name: Publish
                  command: ./scripts/npm-publish.sh

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
    build-test-maybe-publish:
        jobs:
            - build-and-test
            - publish:
                  context: spaceshard
                  filters:
                      branches:
                          only:
                              - master
                  requires:
                      - build-and-test
